spring:
  profiles:
    active: dev
  application:
    name: user-center
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zzd
    url: jdbc:mysql://localhost:3306/yupi
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 1
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost #设置cookie的作用域
#    session:
#      cookie:
#        domain:

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete #全局逻辑删除的实体字段名
      logic-delete-value: 1
      logic-not-delete-value: 0